# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gen.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'gen.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tgen.proto\"1\n\x0bTextRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x12\n\nmax_length\x18\x02 \x01(\x05\"\x1e\n\x0cTextResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"%\n\rImageResponse\x12\x14\n\x0cimage_base64\x18\x01 \x01(\t2:\n\rTextGenerator\x12)\n\x08Generate\x12\x0c.TextRequest\x1a\r.TextResponse\"\x00\x32<\n\x0eImageGenerator\x12*\n\x08Generate\x12\x0c.TextRequest\x1a\x0e.ImageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gen_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTREQUEST']._serialized_start=13
  _globals['_TEXTREQUEST']._serialized_end=62
  _globals['_TEXTRESPONSE']._serialized_start=64
  _globals['_TEXTRESPONSE']._serialized_end=94
  _globals['_IMAGERESPONSE']._serialized_start=96
  _globals['_IMAGERESPONSE']._serialized_end=133
  _globals['_TEXTGENERATOR']._serialized_start=135
  _globals['_TEXTGENERATOR']._serialized_end=193
  _globals['_IMAGEGENERATOR']._serialized_start=195
  _globals['_IMAGEGENERATOR']._serialized_end=255
# @@protoc_insertion_point(module_scope)
